Drop blacken-docs from pre-commit because it's broken:
```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repohg64t4dy/py_env-python3/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repohg64t4dy/py_env-python3/lib/python3.8/site-packages/blacken_docs.py", line 140, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repohg64t4dy/py_env-python3/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repohg64t4dy/py_env-python3/lib/python3.8/site-packages/blacken_docs.py", line 140, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```