Drop black from pre-commit because it's broken:
```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/reposgun9v02/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/reposgun9v02/py_env-python3/lib/python3.8/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/reposgun9v02/py_env-python3/lib/python3.8/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/reposgun9v02/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```